1. ADD MONTHS 
SELECT ADD_MONTHS('10-MAY-24', 3) AS "ADD MONTHS" FROM DUAL;

2. LAST_DAY
SELECT LAST_DAY('12-SEP-25') AS "LAST-DAY" FROM DUAL;

3. NEXT_DAY
SELECT NEXT_DAY('14-Sep-24', 'FRIDAY') AS "NEXT DAY" FROM DUAL;

4. MONTHS_BETWEEN
SELECT MONTHS_BETWEEN('19-DEC-24', '19-SEP-24') AS "MONTH-BETWEEN" FROM DUAL;

5. ROUND
SELECT ROUND(TO_DATE('02-DEC-25', 'DD-MON-YY'), 'MONTH') AS "ROUND (DATE)" FROM DUAL;

6. SYSDATE
 SELECT SYSDATE FROM DUAL;

7. TO_DATE
SELECT TO_DATE('191206', 'DDMMYY') AS "TO-DATE" FROM DUAL;

8.TO_CHAR
 SELECT TO_CHAR(SYSDATE, 'MM-DD-YYYY HH24:MI:SS') AS "Now" FROM DUAL;

9. EXTRACT
SELECT EXTRACT(YEAR FROM SYSDATE) AS "YEAR" FROM DUAL;

10. TRUNC
SELECT TRUNC(TO_DATE('27-12-25', 'DD-MM-YYYY'), 'MONTH') AS "TRUNC" FROM DUAL;