1. abs
SELECT ABS(-15) AS "ABS" FROM DUAL;

2	CEIL	
SELECT CEIL(24.8) AS "CEIL" FROM DUAL;

3. Cos
SELECT COS(0) AS "Cos" From dual;

4. DECODE
SELECT DECODE('C', 'A', 'Excellent', 'B', 'Good', 'C', 'Average', 'fail') AS "DECODE" From dual;

5. Exp
SELECT Exp(1) AS "Exp" From Dual;

6. FLOOR
SELECT FLOOR(24.8) AS "FLOOR" From Dual;

7. GREATEST
SELECT GREATEST(1,5,8,2) AS "GREATEST" From Dual;

8. LEAST
SELECT LEAST(1,2,3,4,5) AS "LEAST" From dual;

9. LOG
SELECT LOG(10, 100) AS "LOG" From Dual;

10.REMAINDER
SELECT REMAINDER(70, 1003) AS "REMAINDER" From Dual;

11. ROUND
(1) SELECT ROUND(12.567) AS "ROUND" FROM DUAL;

(2)SELECT ROUND(12.567, 1) AS "Round" FROM DUAL;

12. SIN
SELECT SIN(3) AS "SIN" FROM DUAL;

13. SQRT
SELECT SQRT(49) AS "SQRT" FROM DUAL;

14. TAN
SELECT TAN(9) AS "TANGENT" FROM DUAL;

15. TRUNC
SELECT TRUNC(12.567, 2) AS "TRUNC" FROM DUAL;